resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(889acb63-3714-4edc-bfce-8f54f2c07c00)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'embersilk-sf-rg'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'template.json'
    csmParametersFile: 'parameters.json'
    deploymentMode: 'Incremental'
    overrideParameters: '{"adminPassword":"$(admin_password)","adminUserName":"$(admin_username)"}'
